POST localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc1NjI4OTE1OSwidXNlcklkIjoxfQ.4zR7JvMdQ9spgLIrYn8ODy2_OetBHdO8fySiqNIECOU

{
  "name": "Party",
  "description": "This is a test event",
  "dateTime": "2025-10-01T10:00:00Z",
  "location": "Berlin"
}