PUT localhost:8080/events/1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc1NjIxNjMxMCwidXNlcklkIjoyfQ.uus6IvyWuiHbocbO1gn6UWlDXk6oEVBIG2MzggnEmxM

{
  "name": "new updated name",
  "description": "This is a updated test event",
  "dateTime": "2025-10-02T10:00:00Z",
  "location": "Berlin"
}